# Generated by Django 4.1.1 on 2022-10-24 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sc_admin', '0003_adminlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=20)),
                ('s_uname', models.CharField(max_length=25)),
                ('s_gender', models.CharField(max_length=10)),
                ('s_dob', models.CharField(max_length=20)),
                ('s_password', models.CharField(max_length=10)),
                ('s_photo', models.ImageField(upload_to='student/')),
                ('s_address', models.CharField(max_length=60)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sc_admin.teacher')),
            ],
        ),
    ]
