# Generated by Django 4.1.1 on 2022-11-03 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='s_photo',
        ),
    ]
