# Generated by Django 4.1.1 on 2022-10-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=25)),
                ('qualification', models.CharField(max_length=20)),
                ('experience', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='teacher/')),
                ('address', models.CharField(max_length=60)),
            ],
        ),
    ]
