# Generated by Django 4.1.1 on 2022-10-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc_admin', '0002_rename_experience_teacher_exp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=20)),
                ('admin_password', models.CharField(max_length=20)),
            ],
        ),
    ]
