# Generated by Django 4.1.1 on 2022-11-03 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student1',
            old_name='s_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='student1',
            old_name='s_dob',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='student1',
            old_name='s_gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='student1',
            old_name='s_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student1',
            old_name='s_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='student1',
            old_name='s_uname',
            new_name='uname',
        ),
    ]
